# Generated by Django 2.2.4 on 2019-09-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('projector', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_reserv.Room')),
            ],
            options={
                'unique_together': {('reservation_date', 'rooms')},
            },
        ),
    ]
